### ISSUE TITLE
Is it better to add  validation-mode?

### ISSUE THREAD

**Issue by shtse8** [BlockMatrixNetwork/eos-mainnet#10]
I notice that the current default config hasn't `validation-mode = light`.
Is it better to add this for better performance? Or there is some other reasons or drawback behind to not add this?

**Comment by pete001** [comment]
Hey @shtse8 the general rule of thumb is that once your environment has validated a block, all of your interior nodes could run `validation-mode = light`. 

As API nodes tend to be the first point of contact with the external network, it's generally regarded that they would process with `full`, and seed/producing nodes would be `light`. 

You could definitely use `light` whilst rebuilding though to speed things up.

**Comment by pete001** [comment]
You know, i have followed up on this, and it seems that it is the opposite way around these days! I am updating the config in the repo with this :-)

**Comment by pete001** [comment]
Testing a full blocks replay before merging.

**Comment by pete001** [comment]
Merged.
