### ISSUE TITLE
support system

### ISSUE THREAD

**Issue by cryptopeng** [BlockMatrixNetwork/eos-mainnet#14]
only support ubuntu?

**Comment by cryptopeng** [comment]
when i want to deploy eos on centos 7.4:
➜  eos-mainnet git:(master) ✗ ansible-playbook eos.yml

PLAY [mainnet] *******************************************************************************************************************************************************************

TASK [install python2] ***********************************************************************************************************************************************************
changed: [120.79.103.136]

TASK [deploy : Installing dependencies] ******************************************************************************************************************************************
failed: [120.79.103.136] (item=['git', 'build-essential', 'python-simplejson', 'python-pexpect', 'jq']) => {"changed": false, "cmd": "apt-get update", "item": ["git", "build-essential", "python-simplejson", "python-pexpect", "jq"], "msg": "[Errno 2] 没有那个文件或目录", "rc": 2}
	to retry, use: --limit @/Users/wanpeng/Rdd/eos-mainnet/eos.retry

PLAY RECAP ***********************************************************************************************************************************************************************
120.79.103.136             : ok=1    changed=1    unreachable=0    failed=1

**Comment by pete001** [comment]
Yes, unfortunately we only support ubuntu at this time. 

We'd love a PR for multi OS support though!
