### ISSUE TITLE
History plugin

### ISSUE THREAD

**Issue by p-fedyukovich** [BlockMatrixNetwork/eos-mainnet#15]
Hi, Pete
After replay I can not fetch historical data, API gives response no data found
Could you explain how to enable history plugin? Does it need enabled plugin before replay?

**Comment by pete001** [comment]
Hey there, 

Yes we run this repo with history disabled as it requires too much machine resource. 

If you want to enable, simply add the following to the config:

```
plugin = eosio::history_plugin
plugin = eosio::history_api_plugin
```

And you can choose what to index with `filter-on = ...`

**Comment by p-fedyukovich** [comment]
Hi again,
Thank you for the answer.
Passing this configuration has enabled historical actions, but transactions can not be found
"what": "The transaction can not be found",

**Comment by pete001** [comment]
Once you enable it, it will only index from that point forward. 

If you want all the retrospective history data, you will need to replay.

**Comment by p-fedyukovich** [comment]
It has been replayed with enabled plugin.
