### ISSUE TITLE
Could not find or access /.../requirements.yml

### ISSUE THREAD

**Issue by murray1337** [BlockMatrixNetwork/eos-mainnet#2]
$ .. /home/accname/eos-mainnet# ansible-playbook eos.yml

ERROR! Unable to retrieve file contents
Could not find or access '/home/accname/eos-mainnet/requirements.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

I do not see requirements.yml in the folder eos-mainnet.
Just followed the instructions as given. I'm on Ubuntu 16.04 Digital Ocean

**Comment by pete001** [comment]
Thanks for flagging this, it is now fixed 👍
