### ISSUE TITLE
Meet error when install eos

### ISSUE THREAD

**Issue by littlekfc** [BlockMatrixNetwork/eos-mainnet#3]
ubuntu@ip-172-31-21-21:~/eos-mainnet$ ansible-playbook eos.yml 
ERROR! no action detected in task

The error appears to have been in '/home/ubuntu/eos-mainnet/deploy/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- import_tasks: requirements.yml
  ^ here

**Comment by pete001** [comment]
Hey @littlekfc can you please confirm the version of ansible you are using?

**Comment by littlekfc** [comment]
ubuntu@ip-172-31-21-21:~/eos-mainnet$ ansible --version
ansible 2.0.0.2
  config file = /home/ubuntu/eos-mainnet/ansible.cfg
  configured module search path = Default w/o overrides

**Comment by littlekfc** [comment]
I update the ansible and then meet new issue:

PLAY [mainnet] ***********************************************************************************************************************************************

TASK [install python2] ***************************************************************************************************************************************
fatal: [52.77.224.66]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}
        to retry, use: --limit @/home/ubuntu/eos-mainnet/eos.retry

PLAY RECAP ***************************************************************************************************************************************************
52.77.224.66               : ok=0    changed=0    unreachable=1    failed=0

**Comment by pete001** [comment]
Ok great, i will add the ansible version check to the readme. 

As for that error, it is expecting you to have key auth for ssh to your 52.77.224.66 node. How do you normally ssh to this server?

**Comment by littlekfc** [comment]
Yeah. I have solved the issue after ssh-keygen.

**Comment by pete001** [comment]
Cool 👍
