### ISSUE TITLE
How to add config to the playbook?

### ISSUE THREAD

**Issue by shtse8** [BlockMatrixNetwork/eos-mainnet#9]
We want to enable mongodb plugin by default in the playblook.
How can we do this?

**Comment by pete001** [comment]
Hey @shtse8 you can enable this by updating: `roles/network/templates/mainnet/api.j2` with the relevant parameters from here: https://developers.eos.io/eosio-nodeos/docs/mongo_db_plugin

**Comment by shtse8** [comment]
Thanks.
